### ISSUE TITLE
Incompatible Python workflow library in macOS 10.12.4+

### ISSUE THREAD

**Issue by EvilOatmeal** [MuppetGate/Alfred-Workflows-DateCalculator#13]
With these versions...

* Date Calculator: 2.7
* Alfred: 3.7 [938]
* macOS: Mojave 10.14 (18A391)

I see the following message in the Date Calculator workflow view in the Alfred settings...

> This workflow contains a python library incompatible with macOS Sierra 10.12.4+
>
> Click here to find out how to update.

Clicking leads to this page: https://www.alfredapp.com/help/troubleshooting/incompatible-python-workflow-library/

So there's a 3rd party fix, but it would be nice if this was fixed in this workflow directly so the fix doesn't need to be applied when setting up a new computer.

**Comment by MuppetGate** [comment]
Heh. Forgot to comment.

Right, I've upgraded the library and put the new version back on Packal
